### ISSUE TITLE
Can't use IsGranted in combinason with the UserValueResolver

### ISSUE THREAD

**Issue by jvasseur** [sensiolabs/SensioFrameworkExtraBundle#574]
If you use the `UserValueResolver` to inject your user into a controller while using an `IsGranted` (or `Security`) annotation to limit the access to authenticated users like this

```php
/**
 * @IsGranted("ROLE_USER")
 */
public function myAction(UserInterface $user)
{
}
```

 you will get a 500 error for anonymous users because arguments resolving is done before triggering the listener that handle those annotations.

I'm not sure what is the best may solve this issue:
 - Putting the listener back to the controller event means we can't make decisions based on resolved arguments (unless we call the `ArgumentResolver` from the listener but that means running the resolving logic twice).
 - We could make the `UserValueResolver` throw a security exception if the user is anonymous, but it means the `IsGranted` annotation will still be ignored (and thus custom exception messages and status code wouldn't work).
 - We could make the argument resolving not throw immediately but instead wait after the `CONTROLLER_ARGUMENTS` event is dispatched to throw for missing arguments.

**Comment by stof** [comment]
Running the listener after resolving arguments is a must-have, as we want to be able to vote on arguments.

For the case of UserInterface failing when you are not authenticated, this does not come from this bundle.

**Comment by jvasseur** [comment]
@stof yes it doesn't come from this bundle but it's the combination of using the `UserValueResolver` with the `IsGranted` annotation that doesn't work as expected.

And I'm aware we need the resolved arguments to allow voting on them, that's why I opened this issue instead of trying a fix (because I'm not sure how this should be fixed).

**Comment by stof** [comment]
Well, what is not working in your case is converting the `UserInterface` argument on a URL where you are not authenticated. Removing `@IsGranted` will still produce the same issue. This bundle is not involved in the 500 error. So this should be reported to Symfony instead, where the UserValueResolver is implemented.

**Comment by HeahDude** [comment]
The user is not resolved from the url but from the token storage while using the UserValueResolver (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Controller/UserValueResolver.php#L50).
So the problem also happens with `@Security`, and is for now a limitation, both annotations cannot be used while resolving the security user as controller argument.

As said in OP, this is not easy to solve in symfony core nor this bundle.

The workaround would be to make the argument nullable so the resolver can do its job. Then the controller does not have to check for an instance in its implementation since the annotation would have ensured that a user is authenticated before it's executed.

**Comment by Big-Shark** [comment]
@stof @fabpot Any news about this problem?

**Comment by jvasseur** [comment]
This should be fixed by https://github.com/symfony/symfony/pull/45761
